import AppColors from '../theme/colors';

export const pokedexList = [
  {
    id: '001',
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    number: 'Nº001',
    color: AppColors.Grama,
  },
  {
    id: '002',
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    number: 'Nº002',
    color: AppColors.Grama,
  },
  {
    id: '003',
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    number: 'Nº003',
    color: AppColors.Grama,
  },
  {
    id: '004',
    name: 'Charmander',
    types: ['Fire'],
    number: 'Nº004',
    color: AppColors.Fire,
  },
  {
    id: '005',
    name: 'Charmeleon',
    types: ['Fire'],
    number: 'Nº005',
    color: AppColors.Fire,
  },
  {
    id: '006',
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    number: 'Nº006',
    color: AppColors.Fire,
  },
  {
    id: '007',
    name: 'Squirtle',
    types: ['Water'],
    number: 'Nº007',
    color: AppColors.Water,
  },
  {
    id: '008',
    name: 'Wartortle',
    types: ['Water'],
    number: 'Nº008',
    color: AppColors.Water,
  },
  {
    id: '009',
    name: 'Blastoise',
    types: ['Water'],
    number: 'Nº009',
    color: AppColors.Water,
  },
  {
    id: '015',
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    number: 'Nº015',
    color: AppColors.Bug,
  },
  {
    id: '025',
    name: 'Pikachu',
    types: ['Electric'],
    number: 'Nº025',
    color: AppColors.Electric,
  },
  {
    id: '035',
    name: 'Clefairy',
    types: ['Fairy'],
    number: 'Nº035',
    color: AppColors.Fairy,
  },
  {
    id: '051',
    name: 'Dugtrio',
    types: ['Ground'],
    number: 'Nº051',
    color: AppColors.Ground,
  },
  {
    id: '095',
    name: 'Onix',
    types: ['Rock', 'Ground'],
    number: 'Nº095',
    color: AppColors.Rock,
  },
  {
    id: '108',
    name: 'Lickitung',
    types: ['Normal'],
    number: 'Nº108',
    color: AppColors.Normal,
  },
  {
    id: '109',
    name: 'Koffing',
    types: ['Poison'],
    number: 'Nº109',
    color: AppColors.Poison,
  },
  {
    id: '151',
    name: 'Mew',
    types: ['Psychic'],
    number: 'Nº151',
    color: AppColors.Fighting,
  },
  {
    id: '245',
    name: 'Suicune',
    types: ['Water'],
    number: 'Nº245',
    color: AppColors.Water,
  },
  {
    id: '306',
    name: 'Aggron',
    types: ['Steel', 'Ground'],
    number: 'Nº306',
    color: AppColors.Steel,
  },
  {
    id: '384',
    name: 'Rayquaza',
    types: ['Dragon'],
    number: 'Nº384',
    color: AppColors.Fighting,
  },
  {
    id: '448',
    name: 'Lucario',
    types: ['Fighting', 'Steel'],
    number: 'Nº448',
    color: AppColors.Dark,
  },
  {
    id: '497',
    name: 'Serperior',
    types: ['Grass'],
    number: 'Nº497',
    color: AppColors.Grama,
  },
  {
    id: '571',
    name: 'Zoroark',
    types: ['Dark'],
    number: 'Nº571',
    color: AppColors.Dark,
  },
  {
    id: '609',
    name: 'Chandelure',
    types: ['Ghost', 'Fire'],
    number: 'Nº609',
    color: AppColors.Dragon,
  },
  {
    id: '613',
    name: 'Cubchoo',
    types: ['Ice'],
    number: 'Nº613',
    color: AppColors.Ice,
  },
  {
    id: '733',
    name: 'Toucannon',
    types: ['Flying', 'Normal'],
    number: 'Nº733',
    color: AppColors.Flying,
  },
];
