import AppColors from '../theme/colors';

export const pokedexList = [
  {
    id: '001',
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    number: 'Nº001',
    color: AppColors.Grama,
    weight: 6.9,
    height: 0.7,
    category: 'Seed',
    ability: 'Overgrow',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
    developments: ['Nº001', 'Nº002', 'Nº003'],
    desc: 'There is a plant seed on its back from the day this Pokémon is born. The seed grows slowly.',
  },
  {
    id: '002',
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    number: 'Nº002',
    color: AppColors.Grama,
    weight: 13.0,
    height: 1.0,
    category: 'Seed',
    ability: 'Overgrow',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
    developments: ['Nº001', 'Nº002', 'Nº003'],
    desc: 'When the lump on its back grows, it seems to lose the ability to stand on its hind legs.',
  },
  {
    id: '003',
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    number: 'Nº003',
    color: AppColors.Grama,
    weight: 100,
    height: 2.0,
    category: 'Seed',
    ability: 'Overgrow',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
    developments: ['Nº001', 'Nº002', 'Nº003'],
    desc: 'Your plant blooms when it is absorbing solar energy. It stays in motion to seek sunlight.',
  },
  {
    id: '004',
    name: 'Charmander',
    types: ['Fire'],
    number: 'Nº004',
    color: AppColors.Fire,
    weight: 8.5,
    height: 0.6,
    category: 'Lizard',
    ability: 'Blaze',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Water', 'Ground', 'Rock'],
    developments: ['Nº004', 'Nº005', 'Nº006'],
    desc: 'It prefers hot things. When it rains, steam is said to pour from the tip of its tail.',
  },
  {
    id: '005',
    name: 'Charmeleon',
    types: ['Fire'],
    number: 'Nº005',
    color: AppColors.Fire,
    weight: 19.0,
    height: 1.1,
    category: 'Flame',
    ability: 'Blaze',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Water', 'Ground', 'Rock'],
    developments: ['Nº004', 'Nº005', 'Nº006'],
    desc: 'It has a savage nature. In battle, it lashes its fiery tail and slashes with sharp claws.',
  },
  {
    id: '006',
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    number: 'Nº006',
    color: AppColors.Fire,
    weight: 90.5,
    height: 1.7,
    category: 'Flame',
    ability: 'Blaze',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Water', 'Electric', 'Rock', 'Ice'],
    developments: ['Nº004', 'Nº005', 'Nº006'],
    desc: 'It breathes fire hot enough to melt boulders. It can start forest fires by blowing flames.',
  },
  {
    id: '007',
    name: 'Squirtle',
    types: ['Water'],
    number: 'Nº007',
    color: AppColors.Water,
    weight: 9.0,
    height: 0.5,
    category: 'Tiny Turtle',
    ability: 'Torrent',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Grass', 'Electric'],
    developments: ['Nº007', 'Nº008', 'Nº009'],
    desc: 'When it retracts its long neck into its shell, it squirts water with vigorous force.',
  },
  {
    id: '008',
    name: 'Wartortle',
    types: ['Water'],
    number: 'Nº008',
    color: AppColors.Water,
    weight: 22.5,
    height: 1.0,
    category: 'Turtle',
    ability: 'Torrent',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Grass', 'Electric'],
    developments: ['Nº007', 'Nº008', 'Nº009'],
    desc: 'It is recognized as a symbol of longevity. If the shell has algae on it, that Wartortle is very old.',
  },
  {
    id: '009',
    name: 'Blastoise',
    types: ['Water'],
    number: 'Nº009',
    color: AppColors.Water,
    weight: 85.5,
    height: 1.6,
    category: 'Shellfish',
    ability: 'Torrent',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Grass', 'Electric'],
    developments: ['Nº007', 'Nº008', 'Nº009'],
    desc: 'It crushes its enemy beneath its heavy body to cause unconsciousness. In a pinch, it will retreat into its shell.',
  },
  {
    id: '015',
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    number: 'Nº015',
    color: AppColors.Bug,
    weight: 29.5,
    height: 1.0,
    category: 'Poison Bee',
    ability: 'Swarm',
    male: 50,
    female: 50,
    weeknesses: ['Fire', 'Psychic', 'Flying', 'Rock'],
    developments: ['Nº013', 'Nº014', 'Nº015'],
    desc: 'It has three venomous stingers on its front legs and tail. They are used to repeatedly stab its enemy.',
  },
  {
    id: '025',
    name: 'Pikachu',
    types: ['Electric'],
    number: 'Nº025',
    color: AppColors.Electric,
    weight: 6.0,
    height: 0.4,
    category: 'Mouse',
    ability: 'Static',
    male: 50,
    female: 50,
    weeknesses: ['Ground'],
    developments: ['Nº172', 'Nº025', 'Nº026'],
    desc: 'Pikachu, which can generate powerful electricity, has cheek pouches that are extra soft and super stretchy.',
  },
  {
    id: '035',
    name: 'Clefairy',
    types: ['Fairy'],
    number: 'Nº035',
    color: AppColors.Fairy,
    weight: 7.5,
    height: 0.6,
    category: 'Fairy',
    ability: 'Cute Charm Magic Guard',
    male: 25,
    female: 75,
    weeknesses: ['Steel', 'Poison'],
    developments: ['Nº173', 'Nº035', 'Nº036'],
    desc: 'It is said that happiness will come to those who see a gathering of Clefairy dancing under the full moon.',
  },
  {
    id: '051',
    name: 'Dugtrio',
    types: ['Ground'],
    number: 'Nº051',
    color: AppColors.Ground,
    weight: 33.3,
    height: 0.7,
    category: 'Mole',
    ability: 'Sand Veil Areba Trap',
    male: 50,
    female: 50,
    weeknesses: ['Water', 'Grass', 'Ice', 'Rock'],
    developments: ['Nº050', 'Nº051'],
    desc: 'A team of Diglett triplets. It unleashes massive earthquakes by digging 60 miles underground.',
  },
  {
    id: '095',
    name: 'Onix',
    types: ['Rock', 'Ground'],
    number: 'Nº095',
    color: AppColors.Rock,
    weight: 210.0,
    height: 8.8,
    category: 'Rock Snake',
    ability: 'Rock Head Sturdy',
    male: 50,
    female: 50,
    weeknesses: [
      'Steel',
      'Fighting',
      'Flying',
      'Water',
      'Ice',
      'Grass',
      'Ground',
    ],
    developments: ['Nº095', 'Nº208'],
    desc: 'As it digs through the soil, it absorbs many hard objects. That is what makes its body so solid.',
  },
  {
    id: '108',
    name: 'Lickitung',
    types: ['Normal'],
    number: 'Nº108',
    color: AppColors.Normal,
    weight: 65.5,
    height: 1.2,
    category: 'Licking',
    ability: 'Oblivious Own Tempo',
    male: 50,
    female: 50,
    weeknesses: ['Fighting'],
    developments: ['Nº108', 'Nº463'],
    desc: "If this Pokémon's sticky saliva comes into contact with you and you don't wipe it off, an intense itch will set in. The itching won't go away, either.",
  },
  {
    id: '109',
    name: 'Koffing',
    types: ['Poison'],
    number: 'Nº109',
    color: AppColors.Poison,
    weight: 1.0,
    height: 0.6,
    category: 'Poison Gas',
    ability: 'Levitate Neutralizing',
    male: 50,
    female: 50,
    weeknesses: ['Psychic', 'Ground'],
    developments: ['Nº109', 'Nº110'],
    desc: 'Its body is filled with poisonous gas. It floats over landfills, seeking the smoke from raw, rotting garbage.',
  },
  {
    id: '151',
    name: 'Mew',
    types: ['Psychic'],
    number: 'Nº151',
    color: AppColors.Fighting,
    weight: 4.0,
    height: 0.4,
    category: 'New Species',
    ability: 'Synchronize',
    male: 0,
    female: 0,
    weeknesses: ['Ghost', 'Dark', 'Bug'],
    developments: ['Nº095', 'Nº208'],
    desc: "When viewed through a microscope, this Pokémon's short, fine, and delicate hair can be seen.",
  },
  {
    id: '245',
    name: 'Suicune',
    types: ['Water'],
    number: 'Nº245',
    color: AppColors.Water,
    weight: 187.0,
    height: 2.0,
    category: 'Aurora',
    ability: 'Pressure',
    male: 0,
    female: 0,
    weeknesses: ['Grass', 'Electric'],
    developments: ['Nº245'],
    desc: 'Suicune embodies the compassion of a pure water source. It traverses the land with grace.',
  },
  {
    id: '306',
    name: 'Aggron',
    types: ['Steel', 'Ground'],
    number: 'Nº306',
    color: AppColors.Steel,
    weight: 210.0,
    height: 8.8,
    category: 'Rock Snake',
    ability: 'Rock Head Sturdy',
    male: 50,
    female: 50,
    weeknesses: ['Fighting', 'Water', 'Ground'],
    developments: ['Nº394', 'Nº305', 'Nº306'],
    desc: 'Aggron has a horn sharp enough to pierce thick iron plates. It knocks down its opponents by striking them first with its horn.',
  },
  {
    id: '384',
    name: 'Rayquaza',
    types: ['Dragon'],
    number: 'Nº384',
    color: AppColors.Fighting,
    weight: 210.0,
    height: 8.8,
    category: 'Rock Snake',
    ability: 'Rock Head Sturdy',
    male: 50,
    female: 50,
    weeknesses: ['Ice', 'Rock', 'Fairy', 'Dragon'],
    developments: ['Nº384'],
    desc: 'It is said that Rayquaza has lived for hundreds of millions of years. Legends persist regarding how the clash between Kyogre and Groudon ended.',
  },
  {
    id: '448',
    name: 'Lucario',
    types: ['Fighting', 'Steel'],
    number: 'Nº448',
    color: AppColors.Dark,
    weight: 54.0,
    height: 1.2,
    category: 'Aura',
    ability: 'Inner Focus Steadfast',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Fighting', 'Ground', 'Fire'],
    developments: ['Nº447', 'Nº448'],
    desc: 'He controls waves known as auras, which are powerful enough to pulverize massive rocks. He uses these waves to bring down his prey.',
  },
  {
    id: '497',
    name: 'Serperior',
    types: ['Grass'],
    number: 'Nº497',
    color: AppColors.Grama,
    weight: 60.3,
    height: 3.3,
    category: 'Regal',
    ability: 'Overgrow',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Flying', 'Ice', 'Bug', 'Fire', 'Poison'],
    developments: ['Nº495', 'Nº496', 'Nº497'],
    desc: "He only gives it his all against strong opponents who aren't fazed by the gleam in Serperior's noble eyes.",
  },
  {
    id: '571',
    name: 'Zoroark',
    types: ['Dark'],
    number: 'Nº571',
    color: AppColors.Dark,
    weight: 81.1,
    height: 1.6,
    category: 'Illusion Fox',
    ability: 'Illusion',
    male: 87.5,
    female: 12.5,
    weeknesses: ['Fighting', 'Bug', 'Fairy'],
    developments: ['Nº570', 'Nº571'],
    desc: 'This Pokémon cares deeply about others of its kind and will conjure terrifying illusions to keep its den and its pack safe.',
  },
  {
    id: '609',
    name: 'Chandelure',
    types: ['Ghost', 'Fire'],
    number: 'Nº609',
    color: AppColors.Dragon,
    weight: 34.3,
    height: 1.0,
    category: 'Luring',
    ability: 'Flash Fire Flame Body',
    male: 50,
    female: 50,
    weeknesses: ['Dark', 'Ghost', 'Water', 'Rock', 'Ground'],
    developments: ['Nº607', 'Nº608', 'Nº609'],
    desc: 'This Pokémon haunts ruined mansions. It waves its arms to hypnotize opponents with the eerie dance of its flames.',
  },
  {
    id: '613',
    name: 'Cubchoo',
    types: ['Ice'],
    number: 'Nº613',
    color: AppColors.Ice,
    weight: 8.5,
    height: 0.5,
    category: 'Chill',
    ability: 'Snow Cloak Slush Rush',
    male: 50,
    female: 50,
    weeknesses: ['Steel', 'Fighting', 'Rock', 'Fire'],
    developments: ['Nº613', 'Nº614'],
    desc: 'When this Pokémon is healthy, its mucus becomes thicker and stickier. It will smear its mucus on anyone it dislikes.',
  },
  {
    id: '733',
    name: 'Toucannon',
    types: ['Flying', 'Normal'],
    number: 'Nº733',
    color: AppColors.Flying,
    weight: 26.0,
    height: 1.1,
    category: 'Cannon',
    ability: 'Keen Eye Skill Link',
    male: 50,
    female: 50,
    weeknesses: ['Electric', 'Fighting', 'Ice', 'Rock'],
    developments: ['Nº731', 'Nº732', 'Nº733'],
    desc: 'They tap beaks with others of their kind to communicate. The force and number of taps tell each other how they are feeling.',
  },
];
